[package]
name = "quick-junit"
description = "Data model and serializer for JUnit/XUnit XML"
version = "0.4.0"
readme = "README.md"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/nextest-rs/quick-junit"
documentation = "https://docs.rs/quick-junit"
keywords = ["junit", "xunit", "xml", "serializer", "flaky-tests"]
categories = ["encoding", "development-tools"]
edition = "2021"
rust-version = "1.70"

[dependencies]
chrono = { version = "0.4.38", default-features = false, features = ["std"] }
indexmap = "2.2.6"
quick-xml = "0.31.0"
newtype-uuid = "1.1.0"
thiserror = "1.0.60"
strip-ansi-escapes = "0.2.0"
uuid = "1.8.0"

[dev-dependencies]
goldenfile = "1.7.1"
owo-colors = "4.0.0"
