on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: CI
env:
  RUSTFLAGS: -D warnings
  CARGO_TERM_COLOR: always

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - uses: dtolnay/rust-toolchain@4be7066ada62dd38de10e7b70166bc74ed198c30 # stable
        with:
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@82a92a6e8fbeee089604da2575dc567ae9ddeaab # v2
      - name: Install just, cargo-hack, and cargo-sync-rdme
        uses: taiki-e/install-action@c93ccc03e00cd0e08e494f5fd058a6c55a6a1907 # v2
        with:
          tool: just,cargo-hack,cargo-sync-rdme
      - name: Lint (clippy)
        run: just powerset clippy --all-targets
      - name: Lint (rustfmt)
        run: cargo xfmt --check
      # Pin to a specific nightly for compatibility with cargo-sync-rdme.
      - name: Get nightly toolchain version
        id: nightly
        run: echo "toolchain=$(just --evaluate nightly_toolchain)" >> "$GITHUB_OUTPUT"
      - name: Install nightly toolchain for cargo-sync-rdme
        uses: dtolnay/rust-toolchain@fa04a1451ff1842e2626ccb99004d0195b455a88 # master
        with:
          toolchain: ${{ steps.nightly.outputs.toolchain }}
      - name: Regenerate readmes
        run: just generate-readmes
      - name: Check for differences
        run: git diff --exit-code

  build-rustdoc:
    name: Build documentation
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: false
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - uses: dtolnay/rust-toolchain@4be7066ada62dd38de10e7b70166bc74ed198c30 # stable
      - uses: Swatinem/rust-cache@82a92a6e8fbeee089604da2575dc567ae9ddeaab # v2
      - name: Build rustdoc
        run: cargo doc --all-features

  build:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # macos-14 for M1 runners
          - macos-14
          - windows-latest
        # 1.79 is the MSRV
        rust-version: ["1.79", stable]
      fail-fast: false
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - uses: dtolnay/rust-toolchain@fa04a1451ff1842e2626ccb99004d0195b455a88 # master
        with:
          toolchain: ${{ matrix.rust-version }}
      - uses: Swatinem/rust-cache@82a92a6e8fbeee089604da2575dc567ae9ddeaab # v2
        with:
          key: ${{ matrix.rust-version }}
      - name: Install latest nextest release
        uses: taiki-e/install-action@740a936627d24a66436d6a4fc358cb5b3d4b79c5 # nextest
      - name: Install just
        uses: taiki-e/install-action@2523ff1c60d7ec8a723c72fe9d7b61b455409834 # just
      - name: Install cargo-hack
        uses: taiki-e/install-action@df30210819ac9b609b31093c22086af2be3fe3c7 # cargo-hack
      - name: Build quick-junit
        run: just powerset build
      - name: Run tests
        run: just powerset nextest run
      - name: Run doctests
        run: just powerset test --doc
