on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: CI
env:
  RUSTFLAGS: -D warnings
  CARGO_TERM_COLOR: always

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
      - name: Install just, cargo-hack, and cargo-sync-rdme
        uses: taiki-e/install-action@v2
        with:
          tool: just,cargo-hack,cargo-sync-rdme
      - name: Lint (clippy)
        run: just powerset clippy --all-targets
      - name: Lint (rustfmt)
        run: cargo xfmt --check
      # Pin to a specific nightly for compatibility with cargo-sync-rdme.
      - name: Get nightly toolchain version
        id: nightly
        run: echo "toolchain=$(just --evaluate nightly_toolchain)" >> "$GITHUB_OUTPUT"
      - name: Install nightly toolchain for cargo-sync-rdme
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ steps.nightly.outputs.toolchain }}
      - name: Regenerate readmes
        run: just generate-readmes
      - name: Check for differences
        run: git diff --exit-code

  build-rustdoc:
    name: Build documentation
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: false
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
      - name: Build rustdoc
        run: cargo doc --all-features

  build:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # macos-14 for M1 runners
          - macos-14
          - windows-latest
        # 1.79 is the MSRV
        rust-version: ["1.79", stable]
      fail-fast: false
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust-version }}
      - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
        with:
          key: ${{ matrix.rust-version }}
      - name: Install latest nextest release
        uses: taiki-e/install-action@nextest
      - name: Install just
        uses: taiki-e/install-action@just
      - name: Install cargo-hack
        uses: taiki-e/install-action@cargo-hack
      - name: Build quick-junit
        run: just powerset build
      - name: Run tests
        run: just powerset nextest run
      - name: Run doctests
        run: just powerset test --doc
